apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  labels:
    app: guestbook
    tier: frontend
spec:
  type: LoadBalancer # or NodePort if load balancer is not supported
  ports:
  - port: 80
  selector:
    app: guestbook
    tier: frontend
